export const athletes = [
  {
    id: 1,
    firstName: "Mike",
    lastName: "Johnson",
    goal: "Performance",
    currentWeight: 79.4,
    targetWeight: 75,
    compliance: 94,
    calories: 2100,
    calorieGoal: 2200,
    checkedIn: true,
  },
  {
    id: 2,
    firstName: "Sarah",
    lastName: "Lee",
    goal: "Weight Loss",
    currentWeight: 65.8,
    targetWeight: 60,
    compliance: 88,
    calories: 1850,
    calorieGoal: 2000,
    checkedIn: true,
  },
  {
    id: 3,
    firstName: "Alex",
    lastName: "Smith",
    goal: "Competition Prep",
    currentWeight: 91.2,
    targetWeight: 86,
    compliance: 71,
    calories: 2500,
    calorieGoal: 2700,
    checkedIn: false,
  },
];